### ISSUE TITLE
Decode top level array into object's property

### ISSUE THREAD

**Issue by kiliankoe** [Anviking/Decodable#105]
Hi,

I'm getting an array of JSON objects as a response from my API. To keep my sanity, I'm trying to deal with deserialized objects only, and not have lists of objects in there as well. For that I tried wrapping the API response into another object that looks something like this:

```swift
struct Campus {
    let buildings: [Building]
}

extension Campus: Decodable {
    static func decode(_ json: AnyObject) throws -> Campus {
        return try Campus(
            buildings: json => ""
        )
    }
}
```

Just supplying `""` as the key doesn't seem to be working however. Is there a way I can tell Decodable to deserialize the top-level array I'm getting back into the `buildings` property?

The JSON structure looks something like this for reference:

```js
[
    {
        "name": "Building1"
        ...
    },
    {
        "name": "Building2"
        ...
    },
    ...
]
```

**Comment by Anviking** [comment]
This should work:
```swift
return try Campus(
            buildings: [Building].decode(json)
        )
```

I also think you can use an empty array `json => []` if you prefer, but not 100% sure.

**Comment by kiliankoe** [comment]
Awesome, that seems pretty neat! Thanks! 

While on that, I have a similar issue at another point in my code. I'm hoping this isn't stupid 😕 

The model looks like the following. Using `AnyObject` there instead of `String` as my API is stupid and is giving me a mix of `String`s and `Int`s as values (which is totally unnecessary in this context).

```swift
struct AccessibilityInfo {
    let data: [String: AnyObject]
}
```

Decodable doesn't seem to let me just type `data: json => [String: AnyObject].decode(json)` as per your example above. 

Thank you so much for any help!

**Comment by kiliankoe** [comment]
Thinking about it, it looks like just using json directly there would work, and it does seem to be so. 

```swift
static func decode(_ json: AnyObject) throws -> AccessibilityInfo {
    guard let dict = json as? [String: AnyObject] else {
        throw ...
    }
    return AccessibilityInfo(
        data: dict
    )
}
```

**Comment by Anviking** [comment]
👍 `Decodable`-like extensions already exist for Dictionaries where Key and Value: Decodable, will add another for where Value == AnyObject so that `[SomethingDecodable: AnyObject].decode` works.

**Comment by kiliankoe** [comment]
Awesome, thanks! :)
