### ISSUE TITLE
(Help) Adaptive mapping for arrays in model when JSon return single object instead array. 

### ISSUE THREAD

**Issue by nissaba** [Anviking/Decodable#106]
Hi, need some help please. :) 

I have to work with a restService that when needed to return an array that contains 1 object it will remove the brackets leaving the json to be a single object instead of an array containing 1 object as it saves on characters we send over the internet. 

example model: 

Struct example
{
    var names: [String]
}

if I get a json back that is for example return 1 name i get
{
   "names": "Donnald"
}

and if the json returned as multiple names then I get 

{
    "names":["Donald", "Daffy", "Neptune"]
}

From what I read in the info is that this will create a mismatch or I can get a nil using "try? => -> T"

I need to change this so that instead of a nil or a throw it will try to fit the value as to imbed the single value in a array in this way resolving the problem.. same could be done for a number that should be a string or the other way around. some data types can be fitted or adapted and I need the mapping to be able to account for the "inconsistent" result I get with the restService I have to work with. 

Thanks for the help :)

**Comment by Anviking** [comment]
Hi! Would something like this be sufficient?
```swift
func wrapInArrayIfNeeded(_ json: AnyObject) -> AnyObject {
    if json is NSArray {
        return json
    } else {
     return [json]
    }
}
// then
try names = wrapInArrayIfNeeded(json) => "names"
```
It would be great however if the default decoding behaviour could be customised, which I think could be done, will look in to this soon.

**Comment by Anviking** [comment]
If you're using Swift 3 and master, you can now customise the default behaviour!
```swift
NSArray.decoder = { json in
    switch json {
    case let array as NSArray:
            return array
    default:
        return [json]
    }
}
```

**Comment by nissaba** [comment]
thanks this is great :)
