### ISSUE TITLE
Question about MetaDecodable

### ISSUE THREAD

**Issue by fjbelchi** [Anviking/Decodable#11]
Hi @Anviking,

I've been reading the new changes in the code, fantastic job with the errors.

I saw this:

```swift
public protocol MetaDecodable {
    typealias MetaType
    var objects: MetaType {get}
    static func decode(json: AnyObject, type: Decodable.Type) throws -> MetaType
}
```

I'm not sure if `MetaDecodable` is used, could you explain the idea behind please?

Thanks

**Comment by Anviking** [comment]
Hi!

In the first implementation each of `T`, `T?`, `[T]?` etc, only needed one overload each. Now two is needed – one where `rhs: String` and one where `rhs: (AnyObject throws -> T)`. Before it looked kind of  manageable. Now it's getting a bit out of control. 

Especially when considering that `[T?]`, `[T?]?` overloads are missing and that you can nest `Set`, `Dictionary`, `Optional`-types infinitely many times.

`MetaDecodable` was an attempt to have only two overloads for all the generic, decodable-containing types.

Hopefully we will get the ability to do `extension Array: Decodable where Element: Decodable` in Swift and call `Element.decode`.

However it should probably look more like this:

```swift
public protocol MetaDecodable: Decodable {
    typealias MetaType
    typealias ElementType
    
    var value: MetaType {get}
}

public func => <T: MetaDecodable>(lhs: AnyObject, rhs: String) throws -> T.MetaType {
    return try T.decode(lhs => rhs).value
}

public func => <T: MetaDecodable>(lhs: AnyObject, rhs: ((AnyObject) throws -> T)) throws -> T.MetaType {
    return try (rhs(lhs)).value
}

public struct DecodableArray<T: Decodable>: MetaDecodable {
    public var value: [T]
    typealias MetaType = [T]
    typealias ElementType = T
    
    public static func decode(json: AnyObject) throws -> DecodableArray<T> {
        guard let array = json as? [AnyObject] else {
            let info = DecodingError.Info(object: json)
            throw DecodingError.TypeMismatch(type: self, info: info)
        }
        
        var newArray = [T]()
        for obj in array {
            print(obj)
            try newArray.append(T.decode(obj))
        }
        
        return DecodableArray(value: newArray)
    }
}
```
It doesn't work, but I hope you get the idea.
