### ISSUE TITLE
Using my own date formatter

### ISSUE THREAD

**Issue by jordanekay** [Anviking/Decodable#110]
Now that `Date` is decodable, what's the best way to specify a different date format?

**Comment by Anviking** [comment]
Most types that per default conform to `Decodable` now also have the following static property you can set:
```swift
static var decoder: (AnyObject) throws -> DecodedType {get set}
```
So just set it to your previous decode-function and you should be fine.

(Slightly more info here: [readme.md#customization](https://github.com/Anviking/Decodable#customization))
