### ISSUE TITLE
Custom decode NSDate in Swift 2.2

### ISSUE THREAD

**Issue by icanswiftabit** [Anviking/Decodable#111]
Hi,
in one of my class I have `NSDate?` I've added extension to `NSDate` so that it can be decodeable and it looks like this.

``` Swift
extension NSDate:Decodable {
    enum NSDateDecodingError:ErrorType {
        case InvalidStringFormat
    }

    public class func decode(json: AnyObject) throws -> Self {
        let string = try String.decode(json)

        let f = NSDateFormatter()
        f.locale = NSLocale(localeIdentifier: "pl_PL")
        f.dateFormat = "yyyy-MM-dd hh:mm:ss Z zzz"

        guard let date = f.dateFromString(string) else {
            log.error("Wrong string format: \(string)")
            throw NSDateDecodingError.InvalidStringFormat
        }

        return self.init(timeIntervalSince1970: date.timeIntervalSince1970)
    }
}
```

Struct that holds dates 

``` Swift
struct CouponJSON:Decodable {
    let name:String?
    let validFrom:NSDate?
    let validTo:NSDate?

    static func decode(j: AnyObject) throws -> CouponJSON {
        return try CouponJSON(
            name: j =>? "name" ,
            validFrom: try j =>? "valid_from",
            validTo: try j =>? "valid_to")
    }
}
```

I've issue with situations when `String` for date is not valid and then whole decoding is stoped. How properly implement Decodable protocol with NSDate?

**Comment by Anviking** [comment]
Hi! I'm not sure what you're specifically trying to achieve, but I take it that you want to return nil instead of throwing if the string is invalid? (please correct me otherwise)

Unfortunately that isn't supported by the `Decodable` protocol. You could write `try? j => "valid_from"` though to catch all errors. Or you could skip it altogether since dateFromString already returns an optional:
```swift
// global
let dateFormatter: NSDateFormatter = {
   let f = 
   ...
   return f
}()

// in decode
valid_from: dateFormatter.dateFromString(j => "valid_from") // only throws if valid_from is not a string
```

**Comment by voidref** [comment]
Not sure if this will help, but here's how I implemented this for a project I worked on:

`
extension NSDate: Decodable {
    public static func decode(json: AnyObject) throws -> Self {
        let dateString = try String.decode(json)
        
        guard let date = Gradiate.dateFormatter.dateFromString(dateString) else {
            throw RawRepresentableInitializationError(type: NSDate.self, rawValue: dateString, object: json)
        }
        
        return self.init(timeIntervalSince1970: date.timeIntervalSince1970)
    }
}
`

Where Gradiate.dateFormatter is a special case of an NSDateFormatter that has the specific format and locale that I was expecting.
