### ISSUE TITLE
Making Array conform to Decodable

### ISSUE THREAD

**Issue by delannoyk** [Anviking/Decodable#116]
Hi there,
Thanks to all contributors for the work on this project, this is my favorite framework to parse JSON yet.
Anyway, I'd like to have your insights on making `Array` conform to `Decodable` instead of "just" adding `decode(...)` on `Array` where `Element: Decodable`.

Although, it would have more sense to conform to Decodable only for Element that are Decodable, this isn't possible (yet?). The extension below could be useful for parsing generic structs where `T` is `Decodable` (a single `Element` or an `Array`).

This is a quick draft I wrote (still Swift 2.3):

``` swift
extension Array: Decodable {
    public static func decode(json: AnyObject) throws -> [Element] {
        if let type = Element.self as? Decodable.Type {
            return try decodeArrayAsOneOf(json, objectTypes: type).flatMap { $0 as? Element }
            //or (since the type has been checked before, we can safely force unwrap).
            return try decodeArrayAsOneOf(json, objectTypes: type).map { $0 as! Element }
        }
        throw TypeMismatchError
    }
}
```

**Comment by Anviking** [comment]
Hi, glad you like it! Are you aware of the ```let a: [String] = try json => "a"``` overloads? As I see it this only moves compile time constraints to the runtime.  Conditional protocol conformance is hopefully coming soon to Swift, but in the meantime nested `Dictionary`, `Array` and `Optional`s should be handled by the generated operator overloads.

(Could see how this applies to custom generic structs, but then they're not included in this library)
