### ISSUE TITLE
Ambiguous use of 'decode' over Dictionary (Xcode8b6)

### ISSUE THREAD

**Issue by poolqf** [Anviking/Decodable#119]
Hi!

I am having troubles decoding an object that its output is a dictionary (`[String : Model]`)

Let's say I have the following JSON.
```swift
        let json = [
            "1" : [
                "id" : "111",
                "name" : "firstName"
            ],
            "2" : [
                "id" : "222",
                "name" : "secondName"
            ]
        ]
```

What I used to do to get the Decoded objects was:

```swift
        let result = try! [String : Model].decode(json)
```

And everything was working fine in Xcode8b3. But today I migrated to Xcode8b6 and this is not working anymore. Xcode is emitting the following error:

<img width="848" alt="screen shot 2016-08-25 at 17 42 39" src="https://cloud.githubusercontent.com/assets/7887319/17975788/58b5d880-6aeb-11e6-9959-ce424937f69e.png">

Seems like is finding to definitions for the `decode` func. But if try to call the `decode` func from a Decodable object, or even an array of Decodable objects, everything works.

I've created a super dummy project that reproduces it, I'm attaching it.

[TestDecodable.zip](https://github.com/Anviking/Decodable/files/437446/TestDecodable.zip)

Thanks a lot

**Comment by Anviking** [comment]
Thanks for reporting. I've removed the [Decodable: Any].decode overload which were causing the ambiguity since beta 6. (Which creates a new problem – #120, but better something's working.)

**Comment by poolqf** [comment]
Thanks @Anviking , everything is working as before ! 👍
