### ISSUE TITLE
Enhancement - spit out swift from given json file

### ISSUE THREAD

**Issue by johndpope** [Anviking/Decodable#128]
you can cherry pick from this code
https://github.com/ijoshsmith/json2swift

for a complex json file - see HTTP Archive
eg.
https://github.com/johndpope/HAR-Reader/blob/master/openlab.har

**Comment by voidref** [comment]
This looks like an interesting idea, kind of equivalent to Protocol Buffers, yes?

I'm not sure that this really aligns well with the intent and scope of the Decodable project.

What I think would make sense is to have a new tool based on `json2swift` with a dependency on `Decodable` for this purpose.

**Comment by johndpope** [comment]
closing this as a spring cleaning exercise. thanks for reply @Anviking
