### ISSUE TITLE
Decoding a class?

### ISSUE THREAD

**Issue by andrew8712** [Anviking/Decodable#134]
I noticed all the examples here use `struct`s. Is the library able to decode classes along with separating the decoding logic from the model itself?

**Comment by andrew8712** [comment]
Answering my own question, this code works just fine:

```
class BaseObject {
    let id: Int

    required init(id: Int) {
        self.id = id
    }
}

extension BaseObject: Decodable {
    static func decode(_ json: Any) throws -> Self {
        return try self.init(id: json => "id")
    }
}
```

The only problem I see it's unable to define an extention for a subclass, as it's already conforming to the protocol:

```
class Object: BaseObject {
    var location: String

    required init(id: Int, location: String) {
        self.location = location
        super.init(id: id)
    }
    
    required init(id: Int) {
        fatalError("init(id:) has not been implemented")
    }
}

```

Is there a workaround?

**Comment by voidref** [comment]
You don't have to conform to `Decodable`, especially for classes which are better used for hierarchies, Decodable was designed around the Struct-as-data-container strategy.

Instead, have a constructor on your class that takes a JSON `Any` and uses Decodable to extract the values of the fields it wants.
