### ISSUE TITLE
Why is NSArray used rather than Array to decode arrays?

### ISSUE THREAD

**Issue by Ricardo1980** [Anviking/Decodable#143]
Hello, 

Why this piece of code is using NSArray rather than Array?

https://github.com/Anviking/Decodable#when-decodable-isnt-enough

Thanks.

**Comment by Anviking** [comment]
`[Any].decode` doesn't exist yet. And if it did exist, it would have just indirectly called `NSArray.decode`. `NSArray` is currently the fundamental `JSON -> Any` function if you will. There might be reason to add `[Any].decode` though.
