### ISSUE TITLE
Anviking should weigh in on Swift Archival and Serialization proposal

### ISSUE THREAD

**Issue by voidref** [Anviking/Decodable#146]
I'm not sure if you have seen this, but there's a proposal in the works for Shelocking Decodable:

https://github.com/itaiferber/swift-evolution/blob/637532e2abcbdb9861e424359bb6dac99dc6b638/proposals/XXXX-swift-archival-serialization.md

Not that it's a bad thing, I think that an official way to do what we are doing here would be great, but I also like how Decodable works.

If you haven't already, perhaps take a moment (ok, a long moment) to read over the proposal and bring up any issues you have, no doubt, run into on the journey of creating this software that they may be missing solutions for.

**Comment by voidref** [comment]
There are now entries in the evolution proposals for this:

[166 Serialization](https://github.com/apple/swift-evolution/blob/master/proposals/0166-swift-archival-serialization.md)
[167 Encoders](https://github.com/apple/swift-evolution/blob/master/proposals/0167-swift-encoders.md)

**Comment by Anviking** [comment]
@voidref how do you respond? Can you just reply to the the review announcement email?

**Comment by voidref** [comment]
Right. 

So, on the Swift-Evolution mailing list, look for the message with the subject:

[swift-evolution] [Review] SE-0166: Swift Archival & Serialization

Here's a link to the mail

https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170403/035163.html

You'll have to subscribe to the list if you aren't already.

**Comment by voidref** [comment]
also:

https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170403/035162.html
