### ISSUE TITLE
Use of unresolved operator

### ISSUE THREAD

**Issue by WeAreUnique** [Anviking/Decodable#156]
I'm using Xcode 9 and Swift 4.
But when I add an example, I got error
`Use of unresolved operator '=>'`
![screen shot 2017-09-24 at 8 07 53](https://user-images.githubusercontent.com/13881055/30782897-2f184624-a164-11e7-99d6-08d0945b7d7d.png)

**Comment by shahbazkhanABMU** [comment]
I am also getting same error... give us the solution

Ambiguous use of operator '=>?'

**Comment by Anviking** [comment]
Is this related to the complexity of the expression?

For instance, does the following compile?
```swift
let id: Int = try json => "id"
```

**Comment by dash-1234** [comment]
Same here :(
Use of unresolved operator '=>'
How to fix this. Structure is similar to above screenshot of 'WeAreUnique' user.

**Comment by Anviking** [comment]
I have not been able to reproduce this. If someone could post a smallest failing example (self-contained and as text) that would be really helpful :)

**Comment by dash-1234** [comment]
@Anviking I will ASAP.

**Comment by dash-1234** [comment]
@Anviking Please have a look on below sample app (TestApp.zip)
Please have look on screen schot as well.
<img width="1089" alt="screen shot 2017-10-02 at 1 39 01 pm" src="https://user-images.githubusercontent.com/1217325/31090978-871d3474-a777-11e7-87b2-8c103c128ac4.png">


[TestApp.zip](https://github.com/Anviking/Decodable/files/1349772/TestApp.zip)

**Comment by dash-1234** [comment]
Please have a look on testApp .
Also have a look on screenshot.
<img width="1089" alt="screen shot 2017-10-02 at 1 39 01 pm" src="https://user-images.githubusercontent.com/1217325/31091451-03ffceba-a779-11e7-8be6-108390485780.png">

[TestApp.zip](https://github.com/Anviking/Decodable/files/1349810/TestApp.zip)

**Comment by Anviking** [comment]
@dash-1234 Thanks! Will take a look.

**Comment by Anviking** [comment]
It was simpler than I expected: we need to `import Decodable` ofc 😅  I will make sure this is clear in the readme. Please let me know if it indeed resolves the issue.

**Comment by dash-1234** [comment]
@Anviking Thank you Man, Error gone :). Thanks a lot.
