### ISSUE TITLE
Add description of changes in the GitHub releases

### ISSUE THREAD

**Issue by AliSoftware** [Anviking/Decodable#158]
The only place where it seem we can see a list of changes for each version is the GitHub releases (as you don't have a CHANGELOG.md), but there are missing entries for some of them, especially the last releases (e.g.: what does 0.6.0 brings me?)

Would be nice to add the list of changes at least for the last 2 👍

**Comment by Anviking** [comment]
Thanks for reminding me! Now done.

**Comment by AliSoftware** [comment]
:tada:
