### ISSUE TITLE
Implementing Decodable for common types

### ISSUE THREAD

**Issue by robertjpayne** [Anviking/Decodable#20]
Hey, I'm trying to allow easy decoding on things like NSURL / NSDate etc… Seems the protocol is complaining when trying to add it to a ObjC class.

Keeps asking 'expected return type to be Self' but if you do that then the return types break.

Have you done this at all?

**Comment by Anviking** [comment]
It can be a bit tricky with classes since subclasses are supposed to return objects of their own type and not of the base class type. I did this for `NSDate`:

```swift
public class func decode(json: AnyObject) throws -> Self {
        let string = try String.decode(json)
        
        guard let date = ISO8601DateFormatter.dateFromString(string) else {
            throw NSDateDecodingError.InvalidStringFormat
        }
        
        return self.init(timeIntervalSince1970: date.timeIntervalSince1970)
```

**Comment by robertjpayne** [comment]
That works, thanks!
