### ISSUE TITLE
Discerning between a custom object and an array is ambiguous because of overloaded operator

### ISSUE THREAD

**Issue by DimaVartanian** [Anviking/Decodable#32]
It seems like arrays should have a separate operator (perhaps '=>|', piped added to regular operator) because receiving an object when expecting an array or vice versa is a valid error case.

Consider the possibility that you are expecting an object of type 'Hat'. Your API is erroneously returning an array of hats so you get [Hat]. Decodable will unfortunately not catch this for you because it doesn't know that you don't want an array.

**Comment by Anviking** [comment]
But there are also a lot of different overloads for non-array stuff. Can't they cause confusion too? Adding separate operators for different things would go against the unformulated but probably existing design philosophy of Decodable that implicit types > explicit in the case of object mapping. And assuming the type-information is preserved, you should really notice that it's an unexpected array *somewhere* in your code.

**Comment by Anviking** [comment]
Oh sorry, did I misunderstand it?

**Comment by DimaVartanian** [comment]
Actually after looking again I think I misunderstood your use of operator overloading (overloading the return type). I believe you were right to close this issue, forget it :)
