### ISSUE TITLE
Does Decodable only work with structs?

### ISSUE THREAD

**Issue by kylebshr** [Anviking/Decodable#37]
I'm trying to use Decodable to create Realm objects, but I'm having issues. Then I realized all the examples were structs — does Decodable not work with classes?

**Comment by Anviking** [comment]
It wasn't designed for it, but yes it should work. Haven't played around with it too much, but know about some problems:
- You must return `Self`. Might be cumbersome sometimes.
- I believe you still can't exit (e.g throw) a class's init-method before all variables are initialized.

The latter should not be a problem though if you have default values on your Realm object.

Have you seen the `NSDate`-example?

```swift
public class func decode(json: AnyObject) throws -> Self {
        let string = try String.decode(json)

        guard let date = ISO8601DateFormatter.dateFromString(string) else {
            throw NSDateDecodingError.InvalidStringFormat
        }

        return self.init(timeIntervalSince1970: date.timeIntervalSince1970)
}
```

**Comment by kylebshr** [comment]
With the NSDate example — if I needed multiple properties, I would have to decode them all, right? 

Here's what I have set up right now, and it's obviously not working. Am I just completely wrong about how it can be used? My knowledge of protocols and the way types work here is not very strong. 
![Returning Self](https://cloud.githubusercontent.com/assets/3526783/10232362/525fe068-6856-11e5-9d0b-0b1d32ef3550.png)
![Returning Test](https://cloud.githubusercontent.com/assets/3526783/10232363/528df6ba-6856-11e5-822e-8ac5787d8b10.png)

**Comment by Anviking** [comment]
What if you do `self.init` instead of `Test`?

**Comment by kylebshr** [comment]
No luck :( 
![screen shot 2015-10-01 at 4 20 01 pm](https://cloud.githubusercontent.com/assets/3526783/10232718/4e509268-6858-11e5-8da9-bb3cd239e885.png)

**Comment by Anviking** [comment]
And if you also make the initializer required?
![skarmavbild 2015-10-01 kl 22 27 22](https://cloud.githubusercontent.com/assets/304423/10232910/b6484f0e-688b-11e5-9b23-027a61f969ac.png)

**Comment by kylebshr** [comment]
Oh wow, I didn't know you could do that — I should read up on my initializers. This seems like it should work great, thank you! Do you see any possible drawbacks or issues doing this?

**Comment by Anviking** [comment]
I guess it might be bad if you subclass a lot. Perhaps this is a little bit better:
![skarmavbild 2015-10-01 kl 22 34 02](https://cloud.githubusercontent.com/assets/304423/10233089/c3982908-688c-11e5-943e-27fa1d464412.png)

**Comment by kylebshr** [comment]
Much better, almost half the code. Thank you!
