### ISSUE TITLE
TypeMismatch NSTaggedPointerString when some attributes are not set to String

### ISSUE THREAD

**Issue by jimjeffers** [Anviking/Decodable#38]
Hi There! I'm really liking your library. I'm currently attempting to decode responses I get from Alamofire's `responseJSON` serializer but I'm encountering issues. Here's a print out of the JSON response. It looks as expected:

```
Optional({
    id = 173722;
    token = 9eea351ff15d43d1609145eb699412cc4297b58d173722;
    user =     {
        "activities_total" = 12780;
        avatar = "https://stagingsite.s3.amazonaws.com/avatars/173722@2.jpeg";
        "avatar_lg" = "https://stagingsite.s3.amazonaws.com/avatars/173722orig.jpeg";
        "competitions_on" = 1;
        converter = 1;
        "first_name" = "";
        gender = Male;
        "giveaway_points_on" = 1;
        "goal_enforced" = 0;
        "inception_date" = "2015-07-27 11:44:11";
        "last_name" = "";
        "last_visit" = "2015-10-02 11:26:04";
        level = 2;
        "levels_and_points" = 1;
        logo = "https://stagingsite.s3.amazonaws.com/logos/saZIvy_mountain-2.jpg";
        "mobilehealth_allowed" = 1;
        "number_of_entries" = 22;
        "pedometer_image" = "https://api.stagingsite.com/_views/images/devices/googlefit32.png";
        "pedometer_last_contact" = 1441394474;
        "pedometer_name" = Googlefit;
        "pedometer_type" = "Google Fit";
        points = 270;
        "points_granted" = 0;
        "points_to_grant" = 36;
        "program_end" = "2017-01-31";
        "program_start" = "2013-10-01";
        "step_average" = 4155;
        "step_goal" = 8000;
        "step_goal_met" = 0;
        "step_total" = 78628;
        "stride_length" = 0;
        "teams_on" = 1;
        "this_device" = "app_name/com. appname.app-name (1; os version 9.0 (build 13a340))";
        "total_privacy" = 0;
        units = Miles;
        url = "beta.stagingsite.com";
        username = somerusername;
    };
    username = someusername;
})
```
Then I have a struct for a UserSession and a User. The issue is that sometimes I'll get an error on attributes that are not set to be a String. For example, several of these attributes should be Bool's or Ints. In some cases this works fine. For example these attributes parse correctly:

```
struct User {
    ...
    var competitionsOn: Int
    var giveawayPointsOn: Bool
    var mobilehealthAllowed: Int
    ...
}
```

But every so often one of the attributes throws this error:

```
TypeMismatch NSTaggedPointerString, expected: Int in user.number_of_entries object: Optional(22)
```

The correct value was found (22) but it's showing up as an Optional. Are there any additional steps I should take when parsing values to describe or cast their type? I currently am just using the most basic implementation per the examples:

```
numberOfEntries: j => "number_of_entries",
```

In any case -- adjusting the attribute type to a String resolves the parsing error but that is not ideal.

**Comment by Anviking** [comment]
Are you sure that (22) really is of an appropriate type when it fails?

**Comment by jimjeffers** [comment]
Yes you're right. The API is returning numeric values inappropriately as strings. Is there a way to easily express to force / cast strings into Ints within the decodable API?

**Comment by Anviking** [comment]
Unfortunately not. You'd have to
```swift
let numberOfEntries = try parse(j, path: ["number_of_entries"]) { object in
    // Do something and return an int
}
```

**Comment by jimjeffers** [comment]
Ah that will work. Unfortunate that I can't control the server but this is sufficient!
