### ISSUE TITLE
Decoding dictionary types

### ISSUE THREAD

**Issue by kiliankoe** [Anviking/Decodable#44]
Hi, this is a question on how to work with Decodable.

I'm talking to an API that gives me a dictionary of the type `Dictionary<String,City>` where `City` is another decodable type. This is the naïve way I tried to start with, but I'm unsure how else to go about this.

```swift
struct Metadata: Decodable {
    ...
    let cities: [String: City]
    
    static func decode(json: AnyObject) throws -> Metadata {
        return try Metadata(
            ...
            cities: json => "cities"
        )
    }
}
```

`TypeMismatch __NSCFDictionary, expected: Dictionary<String, City> in cities object:`

Thanks for any tips! :)

**Comment by Anviking** [comment]
Something like
```swift
public func => <T: Decodable>(lhs: AnyObject, rhs: String) throws -> [String: T] {
    var dict = [String: T]()
    for (key, value) in try NSDictionary.decode(lhs => rhs) {
        try dict[String.decode(key)] = T.decode(value)
    }
    return dict
}
// Dictionary needs to not be Castable to avoid ambiguity
```
My Xcode keeps betraying me now, but will look at this again when I have time.
