### ISSUE TITLE
Default values for missing keys

### ISSUE THREAD

**Issue by djehrlich** [Anviking/Decodable#45]
What's the right way to decode values when the key itself may be missing?  For certain values, I'd like to provide a default value when the key is missing from the JSON.  e.g.

`let memo: String? = try j => "memo" <= nil`

Could Nate Cook's solution for ternary operators in Swift be used? http://natecook.com/blog/2014/10/ternary-operators-in-swift/

**Comment by Anviking** [comment]
Yeah, a lot of cool things could probably be done with that.
You could sort of do
```swift
Apple(color: (try? json => "color") ?? "default")
``` 
already, but it catches every error.
