### ISSUE TITLE
Optional arrays not behaving the way they should

### ISSUE THREAD

**Issue by piercifani** [Anviking/Decodable#5]
First issue 🎉!!!

So, thank you for this awesome piece of code.

I'm finding that optional arrays are not behaving the way they should: expanding on your sample from the README:

```
struct Repository {
    let name: String
    let description: String
    let stargazersCount: Int
    let language: String?
    
    let owner: User
    let defaultBranch: Branch
    let externalContributors: [User]?
    
    var fullName: String { return "\(owner.login)/\(name)" }
}
```

If we add the optional array called `externalContributors` and feed the decode function with a JSON such as: 
```
        let json = [
            "name" : "AwesomeKit",
            "description" : "This is awesome",
            "stargazers_count" : 8,
            "owner" : ["login":"pcifani"],
            "default_branch" : ["branch_name":"master"],
        ]
```
This should be a valid JSON for the `Repository` struct, but it's not, right now, it's returning a `DecodingError.TypeMismatch` with "JSON Array" as the mismatched object.

Let me know if I can help in any way

**Comment by fjbelchi** [comment]
Hi @piercifani I think you are right, I've added a quick test to the suite and If I didn't make any mistake I'm reproducing the same behaviour

**Comment by Anviking** [comment]
Thanks for bringing this up! I added the previously missing `[T]?` returning overload to the `=>` operator, so I think it should work now.

**Comment by piercifani** [comment]
Awesome! it now correctly works!
