### ISSUE TITLE
Missing keys and optionals

### ISSUE THREAD

**Issue by raulriera** [Anviking/Decodable#50]
Hi,

What is the best practice for missing keys? I find it strange (I'm sure I'm wrong here) that the decoding process fails when it founds a missing key and this property is marked as Optional. Is it normal for API responses to not include all the information in their entities for every single call?

I am trying to consume an "index" action that returns some data about the model and a "show" action that shows all the data, but since the "index" is a trimmed down version of the "show" it always fails.

**Comment by Anviking** [comment]
Best practice I don't know, but I used the `=>?` operator which is now removed in favor of Swift's `try?`.

**Comment by Anviking** [comment]
Which would also catch TypeMismatch exceptions, but one could make some fancy operator or helper function to only catch MissingKeys.

**Comment by raulriera** [comment]
Oh that was so obvious

```
extension Property: Decodable {
    static func decode(j: AnyObject) throws -> Property {
        return try Property(
            id: j => "id",
            name: j => "name",
            description: try? j => "description",
            type: j => "type",
            rating: j => "overallRating",
            images: j => "images"
        )
    }
}
```

Would you mind if I include something like this in the README?

**Comment by raulriera** [comment]
Never mind, it's  there already... I am blind 👴🏼

Thanks!

**Comment by Anviking** [comment]
Just added it :stuck_out_tongue:

**Comment by raulriera** [comment]
haha
