### ISSUE TITLE
Decode an array

### ISSUE THREAD

**Issue by deivuh** [Anviking/Decodable#52]
Hi. 

First of all great work with this library, I'd tried quite a few other Swift libraries, and this is the one that worked well with the latest version of RealmSwift for me.

Right now I'm having trouble to parse JSON arrays, if I have the following 

```
coordinates: [-90, 14.4]
```

How should I specify the decoder that I want to parse the latitude and longitude from the array without having the keys?

**Comment by Anviking** [comment]
As of now, you can decode the entire thing as `array = json => "coordinates"` and then do whatever you need to.

**Comment by deivuh** [comment]
Got it, thanks!
