### ISSUE TITLE
Make path, object and rootObject public in DecodingError info struct

### ISSUE THREAD

**Issue by amitvyawahare** [Anviking/Decodable#59]
Decodable reside in a base framework in our project to access path, object and rootObjec from other framework is not possible without making them public. Can you please make that change ? 

    public struct Info {
        
        public init(object: AnyObject, rootObject: AnyObject? = nil, path: [String] = []) {
            self.object = object
            self.rootObject = rootObject
            self.path = path
        }
        
        public var path: [String]
        public var object: AnyObject?
        public var rootObject: AnyObject?
        
        public var formattedPath: String {
            return path.joinWithSeparator(".")
        }
    }

**Comment by Anviking** [comment]
Thanks for bringing this up!
