### ISSUE TITLE
Problem overriding Castable's decode()

### ISSUE THREAD

**Issue by anohren** [Anviking/Decodable#69]
Hej

#### Goal
To additionally make Bool, Int and Double decodable from String values.

#### Best guess

````
extension Bool {
    public static func decode(j: AnyObject) throws -> Bool {
        switch j {
        case is Bool:
            return j as! Bool
        case is String:
            switch j as! String {
            case "true": return true
            case "false": return false
            default: throw DecodingError.UnexpectedValue(value: j, info: DecodingError.Info(object: j))
            }
        default:
            let info = DecodingError.Info(object: j)
            throw DecodingError.TypeMismatch(type: j.dynamicType, expectedType: self, info: info)
        }
    }
}
````

#### Problem
This implementation is not called when doing the usual, e.g.:

````
struct MyDecodableType : Decodable {
    let myBool: Bool

    public static func decode(j: AnyObject) throws -> MyDecodableType {
        return try MyDecodableType(myBool: j => "myBool")
    }
}
````

instead, it only works when doing this:

````
return try MyDecodableType(myBool: try parse(json, path: ["myBool"], decode: Bool.decode))
````

Using this everywhere there's a Bool, Int or Double isn't an option.

`T` should resolve to `Bool` inside of `=>`, but `T.decode` always seems to resolve to Castable's implementation...

Dynamic dispatch seems to follow some simple rules when it comes to instances (https://medium.com/ios-os-x-development/swift-protocol-extension-method-dispatch-6a6bf270ba94#.1wkt1dbt7), but what is going on here?

**Comment by Anviking** [comment]
Hej, sorry, have been busy with school, haven't read up on any method dispatch and cannot directly address the problem. However I would instinctually advocate the use of explicit conversion in some form, perhaps:
```swift
func toBool(j: AnyObject) throws -> Bool {}
MyDecodableType(myBool: toBool(j => "myBool"))
// or even
func fromString<T: FromStringConvirtableOrSomething>(j: AnyObject) throws -> T {}
```

For a moment I thought about implementing your own `BooleanType`, but if it also concerns number types it would probably be indescribably cumbersome.

**Comment by anohren** [comment]
Has this issue been solved?

```
/// Allows overriding default `decode` function from your app.
/// 
/// You likely don't want to conform to this yourself.
public protocol DynamicDecodable {
    associatedtype DecodedType
    
    /// A closure describing how this type should be decoded
    /// 
    /// Types also conforming to `Decodable` call this closure 
    /// from their `decode` function.
    ///
    /// - note: This is intended as a set-once thing.
    static var decoder: (Any) throws -> DecodedType {get set}
}
```

**Comment by Anviking** [comment]
Yeah, should be the case
