### ISSUE TITLE
Does `=>?` actually work as intended?

### ISSUE THREAD

**Issue by irace** [Anviking/Decodable#70]
I can’t figure out for the life of me why the following does not work:

```swift
struct Foo: Decodable {
    let bar: String?

    static func decode(object: AnyObject) throws -> Foo {
        return try Foo(bar: object =>? "bar")
    }
}
```

When parsing the following JSON:

```json
{
  "bar": null
}
```

I would expect `decode` to _not_ throw, and instead return `Foo(bar: nil)`. What happens instead, is `MissingKeyError(key: "bar")`.

**Comment by Anviking** [comment]
Oops, definitely not intended. Should work now though, will bump the version after a double checking a few things.

**Comment by irace** [comment]
Thanks!

**Comment by Anviking** [comment]
Thanks for reporting! On cocoa pods now.

**Comment by irace** [comment]
Thank you!
