### ISSUE TITLE
Should TypeMismatchError.object be of type `Any`?

### ISSUE THREAD

**Issue by JaviSoto** [Anviking/Decodable#72]
Right now you can't construct a `TypeMismatchError` with an optional value. Is this by design?

**Comment by Anviking** [comment]
Didn't know `Any` worked like that, but why would you need `object` to be optional?

**Comment by Anviking** [comment]
`object` is the JSON object that failed to be decoded and will always be an `NSDictionary` or an object contained in a `NSDictionary`, unless you're basically replacing the internals of the library.
