### ISSUE TITLE
Is there any guideline to move from 0.3.4 to 0.4?

### ISSUE THREAD

**Issue by Ricardo1980** [Anviking/Decodable#73]
Is there any guideline to move from 0.3.4 to 0.4?
Or any advice.
I mean, what breaks backwards compatibility?

Thanks a lot.

**Comment by Anviking** [comment]
Have you seen the [releases page](https://github.com/Anviking/Decodable/releases)? Think most notably if you were creating your own errors, they look a bit different now.
