### ISSUE TITLE
decode a Dictionary

### ISSUE THREAD

**Issue by MarvinNazari** [Anviking/Decodable#74]
Hi i get a error when i try decode a Dictionary

```swift
public struct ShowMorePosts {
    public let posts: [STPost]
    public let showMorePosts: [String:[STPost]]
}

extension ShowMorePosts: Decodable {
    public static func decode(j: AnyObject) throws -> ShowMorePosts {
        return try ShowMorePosts(
            posts: j => "posts",
            showMorePosts: j => "show_more_posts"
        )
    }
}

```
Note: STPost is confirming to Decodable
I get this error `Cannot convert value of type 'AnyObject' to expected argument type '[String : [STPost]]'`

**Comment by Anviking** [comment]
We need a `[K: [T]]`-returning overload. Think there are only 2 dictionary-related overloads at the moment, so a lot of useful ones are missing. Will look at it tomorrow. Feel free to beat me in implementing one though. Should just be to copy suiting existing dict overload, but letting the `elementDecodeClosure` be `decodeArray(T.decode)`
