### ISSUE TITLE
Curried function declaration syntax warning in Swift 2.2

### ISSUE THREAD

**Issue by brentleyjones** [Anviking/Decodable#80]
> Decodable.swift:53:27: Curried function declaration syntax will be removed in a future version of Swift; use a single parameter list

**Comment by Anviking** [comment]
Should be fixed with 9c0c78a7ecc74b67a041f7b3e6bbe60de6f2960e, will release a `v0.4.2` now though.

**Comment by Anviking** [comment]
Done!
